plugins {
    id 'java-library'
    id 'net.neoforged.moddev.legacyforge' version '2.0.91'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

sourceSets.main {
    java {
        srcDir 'src/client/java'
        exclude '**/ModMenuIntegration.java'
    }
    resources {
        exclude 'fabric.mod.json'
    }
}

repositories {
    mavenCentral()
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"
    runs {
        client {
            client()
            gameDirectory = file('run')
        }
    }
    mods {
        chronicle {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    jarJar(implementation('javazoom:jlayer:1.0.1')) {
        version {
            strictly '[1.0.1]'
            prefer '1.0.1'
        }
    }
    compileOnly 'com.google.errorprone:error_prone_annotations:2.48.0'
}

def generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    def properties = [
            minecraft_version_range: minecraft_version_range,
            forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version
    ]
    inputs.properties properties
    expand properties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.release = 17
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:all', '-Xlint:-processing']
}

java {
    withSourcesJar()
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

jar {
    from('LICENSE') {
        rename { "${it}_${project.name}" }
    }
    from 'THIRD_PARTY_NOTICES.md'
}
