plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.0.116'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

sourceSets.main {
    java {
        srcDir 'src/client/java'
        exclude '**/ModMenuIntegration.java'
    }
    resources {
        exclude 'fabric.mod.json'
    }
}

repositories {
    mavenCentral()
}

runs {
    configureEach {
        modSource sourceSets.main
    }
    client { }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    implementation 'javazoom:jlayer:1.0.1'
    jarJar('javazoom:jlayer:[1.0.1]') {
        version {
            prefer '1.0.1'
        }
    }
    compileOnly 'com.google.errorprone:error_prone_annotations:2.48.0'
}

def generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    def properties = [
            minecraft_version_range: minecraft_version_range,
            neo_version: neo_version,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version
    ]
    inputs.properties properties
    expand properties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.release = java_version as int
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:all', '-Xlint:-processing']
}

java {
    withSourcesJar()
    toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
}

jar {
    from('LICENSE') {
        rename { "${it}_${project.name}" }
    }
    from 'THIRD_PARTY_NOTICES.md'
}
