org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.1
minecraft_version_range=[26.1]
neo_version=26.1.0.1-beta
loader_version_range=[1,)
java_version=25
legacy_runtime_classpath=false

mod_id=chronicle
mod_name=Chronicle
mod_license=MIT
mod_version=1.3.1+26.1-neoforge
mod_group_id=com.aspectra00.chronicle
