org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.1
loader_version_range=[1,)
java_version=21
legacy_runtime_classpath=true

mod_id=chronicle
mod_name=Chronicle
mod_license=MIT
mod_version=1.3.1+1.21.1-neoforge
mod_group_id=com.aspectra00.chronicle
